html_education/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('', include('mysite.urls'))
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/urls.py
from django.urls import path
from django.urls import include
from . import views





urlpatterns = [
    path('', views.index, name="home"),
    path('blog', views.blog, name="blog"),
    path('post/<int:pk>/', views.post_page, name="post_page"),
    path('all_users', views.all_users, name="all_users"),
    path('user/<int:pk>/', views.user_page, name="user_page"),
    path('profile', views.profile, name="profile"),
    path('post/<int:pk>/', views.post_page),

]

urlpatterns += [
    path('post/create/', views.PostCreate.as_view(), name='post_create'),
    path('post/<int:pk>/update/', views.PostUpdate.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),
]


urlpatterns +=[
    path('reg', views.registr, name ='reg')
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

mysite/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

from django.contrib import auth




class Post(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    title = models.CharField(max_length=100)
    summary = models.TextField(max_length=2000)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE,
                              null=True)
    date = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('post_page', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title


class Comment(models.Model):
    id = models.AutoField(unique=True, primary_key=True)
    post = models.ForeignKey('Post', on_delete=models.SET_NULL, null=True, blank=False)
    name = models.CharField(max_length=80, default=1)
    body = models.TextField(max_length=100, default=1)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE,
                               null=True)
    date = models.DateTimeField(auto_now=True)
    def get_absolute_url(self):
        return reverse('blog')
    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name

mysite/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# Создаём класс формы
class RegistrForm(UserCreationForm):
    # Добавляем новое поле Email
    email = forms.EmailField(max_length=254, help_text='This field is required')

    # Создаём класс Meta
    class Meta:
        # Свойство модели User
        model = User
        # Свойство назначения полей
        fields = ('username', 'email', 'password1', 'password2',)
        fields = ('username', 'email', 'password1', 'password2',)

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')

mysite/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .forms import RegistrForm, CommentForm
from .models import Post, Comment
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


# Create your views here.


def index(request):
    return render(request, 'index.html')

def blog(request):
    context = {
        'posts': Post.objects.all().order_by('date')
    }
    return render(request, 'blog.html', context)


def post_page(request, pk):
    post = Post.objects.get(pk=pk)
    # Список активных комментариев к этой записи
    new_comment = None
    if request.method == 'POST':
        # Комментарий был опубликован
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создайте объект Comment, но пока не сохраняйте в базу данных
            new_comment = comment_form.save(commit=False)
            # Назначить текущий пост комментарию
            new_comment.post = post
            new_comment.author = request.user
            # Сохранить комментарий в базе данных
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request,
                  'post_page.html',
                  {'post': post,
                   'comment' : Comment.objects.filter(post=pk),
                   'new_comment': new_comment,
                   'comment_form': comment_form})

def all_users(request):
    context = {
        'users': User.objects.all()
    }
    return render(request, 'list_of_users.html', context)

def user_page(request, pk):
    context = {
        'user': User.objects.get(pk=pk)
    }
    return render(request, 'user_page.html', context)

def profile(request):
    return render(request, 'profile.html')






class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'summary']
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdate(UpdateView):
    model = Post
    fields = ['title', 'summary']
    success_url = reverse_lazy ('blog')

class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy ('blog')







# Функция регистрации
def registr(request):
    # Массив для передачи данных шаблонны
    data = {}
    # Проверка что есть запрос POST
    if request.method == 'POST':
        # Создаём форму
        form = RegistrForm(request.POST)
        # Валидация данных из формы
        if form.is_valid():
            # Сохраняем пользователя
            form.save()
            # Передача формы к рендару
            data['form'] = form
            # Передача надписи, если прошло всё успешно
            data['res'] = "Всё прошло успешно"
            # Рендаринг страницы
            return redirect('home')
            return render(request, 'registration/registration.html', data)
        else:
            return redirect('reg')

    else: # Иначе
        # Создаём форму
        form = RegistrForm()
        # Передаём форму для рендеринга
        data['form'] = form
        # Рендаринг страницы
        return render(request, 'registration/registration.html', data)

mysite/templates/author_page.html
{% extends "base.html" %}

{% block content %}
    <br>
    <br>
    <br>
    <article>
        <h1>{{author.name}}</h1>
        <p>{{ author.description }}</p>
        <hr>
    <h2>More Posts</h2>
        <hr>
{% for post in author.post_set.all %}
    <article>
        <h3><a href="http://127.00.00.1:8000/post/{{post.id}}">{{post.title}}</a></h3>
    </article>
    <hr>
    {% endfor %}
    </article>
    <hr>
{% endblock %}

mysite/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title> {% block title %}Welcome home{% endblock %} </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js">
  </head>
  <body>
    <br>
  <br>
  <br>

<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">FSociety</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog' %}">BLog</a>
          </li>
          <li class="nav-item">

            <a class="nav-link" href="{% url 'all_users' %}">USers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile' %}">PRofile</a>
          </li>
          <li class="nav-item">

          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>

 {% if user.is_authenticated %}
          <p><a class="btn btn-lg btn-primary" href="/accounts/logout">Logout</a></p>
               {% else %}
          <p><a class="btn btn-lg btn-primary" href="/accounts/login">Login</a></p>
          <p><a class="btn btn-lg btn-primary" href="{% url 'reg' %}">Signup</a></p>

   {% endif %}

        </form>
      </div>
    </div>
  </nav>
</header>
{% block content %} {% endblock %}

mysite/templates/blog.html
{% extends "base.html" %}
{% block title %}blog{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<h1>Post List</h1>
<a href="post/create">Add post</a>
{% for post in posts %}
<article>
<h3><a href=post/{{post.id}}>{{post.title}}</a></h3>
</article>
<hr>
{% endfor %}
{% else %}
<p size="17px">If you want to read posts, you should <a href="reg">register</a> or <a href="/accounts/login">login</a></p>
{% endif %}
{% endblock %}

mysite/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Blog{% endblock %}
{% block content %}

<main>
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Example headline.</h1>
            <p>Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Some representative placeholder content for the three columns of text below the carousel. This is the first column.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>Another exciting bit of representative placeholder content. This time, we've moved on to the second column.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>

        <h2>Heading</h2>
        <p>And lastly this, the third column of representative placeholder content.</p>
        <p><a class="btn btn-secondary" href="#">View details &raquo;</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Some great placeholder content for the first featurette here. Imagine some exciting prose here.</p>
      </div>
      <div class="col-md-5">
<img width="500" height="600" src="{% static 'mysite/img/photo.jpg' %}" alt="Лого">

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <img width="500" height="600" src="{% static 'mysite/img/photo3.jpg' %}" alt="Лого">

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
      </div>
      <div class="col-md-5">
       <img width="500" height="600" src="{% static 'mysite/img/photo4.jpg' %}" alt="Лого">

      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>



    <script src="mysite/staticfiles/JavaScript/bootstrap.bundle.min.js"></script>
{% endblock %}

    <script src="../../static/mysite/JavaScript/bootstrap.bundle.min.js"></script>


  </body>
</html>

mysite/templates/list_of_users.html
{% extends "base.html" %}
{% block title %}All Users{% endblock %}
{% block content %}
    <br>
    <br>
    <br>
    <h1>USer List</h1>
      {% for user in users %}
          <br>
    <article>
        <h3><a href=user/{{user.id}}>{{user.username}}</a></h3>
    </article>
    <hr>
      {% endfor %}

{% endblock %}

mysite/templates/mysite/comment_form.html
{% extends "base.html" %}

{% block content %}
    <br>
    <br>
    <br>
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

mysite/templates/mysite/post_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <br>
    <br>
    <br>
<h1>Delete Post</h1>

<p>Are you sure you want to delete the post: {{ post.title }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete." />
</form>

{% endblock %}

mysite/templates/mysite/post_form.html
{% extends "base.html" %}

{% block content %}
    <br>
    <br>
    <br>
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

mysite/templates/post_page.html
{% extends "base.html" %}

{% block content %}
    <h1>Post</h1>
    <br>
    <article>
        <h1>{{post.title}}</h1><p align="right"><a href="/user/{{post.author.id}}">{{ post.author }}</a></p>
        <p>{{ post.summary }}</p>
        <p align="right">{{ post.date }}</p>
    </article>
    <hr>
    <a href="delete">delete</a>/<a href="update">Update</a>
    <hr>
    <h2>Comments</h2>
    <form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
  </form>
    <hr>
{% for Comment in comment %}
<font size="5">{{ Comment.name }}<br></font>
<font size="4">{{ Comment.body }}<br></font>
<a href="/user/{{Comment.author.id}}">{{ Comment.author }}</a><br>
{{ Comment.date }}
    <hr>
    {% endfor %}
{% endblock %}

mysite/templates/profile.html
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}
    <br>
    <br>
    <br>
    <article>
    <h1>Profile</h1>
        <h1>{{user.username}}</h1>
    </article>
    <hr>
        <p><a class="btn btn-secondary btn-sm" href="/accounts/password_reset">reset password</a></p>
    {% endif %}
{% endblock %}

mysite/templates/user_page.html
{% extends "base.html" %}

{% block content %}
    <br>
    <br>
    <br>
    <article>
        <h1>{{user.username}}</h1>
    </article>
    <hr>
{% endblock %}

mysite/templates/vse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
	a.list:link{
	color: black;
	text-decoration: none;
	font-family:Comic Sans Ms;
	font-weight:bold;
	font-size:14px;
	}
	a.list:visited {
	color: black;
	text-decoration: none;
	}
	a.list:hover{
	color: orange;
	text-decoration: underline;
	}
</style>
</head>
<body>
<p>ghjk</p>
<hr>
<img src="" alt="">
<a rel="nofollow" class="list" href="hg" title="ЖОПА">ывапросмитеол</a>
<hr>
<a href="mailto:as.agafontsev@gmail.com">Gmail</a>
<hr>
<p class="list", style="align-self: center">dhbfjhbdjvb</p>
<hr>
Gjhbjdbvdb><sub>:jgf</sub> #подстрочный <br>
fvdnjfnvkjdnjkv<sup>bsjkhbvd</sup> #надстрочный
<hr>
Jopa<big>Jopa</big> #больше на один пиксель <br>
Jopa<small>Jopa</small> #меньше на один пиксель
<hr>
<ul>
	<li>первый элемент списка</li>
	<li>второй элемент списка</li>
</ul>
<hr>
<table border="1">
<tr><td>1-строка 1 элемент</td><td>1-строка 2 элемент</td></tr>
<tr><td>2-строка 1 элемент</td><td>2-строка 2 элемент</td></tr>
</table>
<hr>
<font style="color:green", size="5px">jdkjfvjdkfjv</font>
<hr>
<h1 class="style1">Jopa</h1>
<h1 class="style2" >Cnhffj dj</h1>

<p >
<p  class="style2"  >dfj ndjsaj dhfajshdfjahsdkjf   haskjdhfnfv   kjdnfkjvn</p>
</p>

<<<<<<< HEAD
<table class="style2" rules="none" background="images/photo.jpg" align="center"
=======
<table class="style2" rules="none" background="../../static/mysite/img/photo.jpg" align="center"
>>>>>>> origin/main
       width="100%" border="1" style="color:white;">
<tr>
	<td colspan="2">
            ndvkjnfkvnkjdnfkjnvkjdncefjkvn
	</td>
</tr>
<tr>
	<td>
		Столбец 1
	</td>
	<td>
		Столбец 2
	</td>
</tr>
</table>
</body>
</html>